# Generated by Django 5.0 on 2024-03-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=3000)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('place', models.CharField(max_length=250)),
                ('Style', models.CharField(max_length=250)),
                ('Attractions', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Fitness',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=3000)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('TimetoVisit', models.CharField(max_length=250)),
                ('HowtoReach', models.CharField(max_length=250)),
                ('Attractions', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Nutrition',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
