# Generated by Django 5.0 on 2024-03-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=3000)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('place', models.CharField(max_length=250)),
                ('Style', models.CharField(max_length=250)),
                ('Attractions', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Health',
            },
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=3000)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('place', models.CharField(max_length=250)),
                ('Style', models.CharField(max_length=250)),
                ('Attractions', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Meditation',
            },
        ),
    ]
